command:
  - "uvicorn"
  - "backend.main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: "CATALOG"
    value: "alexander_booth"
  - name: "SCHEMA"
    value: "maas_summit_team8"
  - name: "LAKEBASE_PROJECT"
    value: "maas-team8"
  - name: "LAKEBASE_BRANCH"
    value: "production"
  - name: "LAKEBASE_DATABASE"
    value: "acme_agency"
  - name: "STATIC_DIR"
    value: "frontend"
