command:
- streamlit
- run
- main.py
env:
- name: MODEL_SERVING_ENDPOINT
  value: agents_alexander_booth-rag_demo-scouting_reports_agent
- name: DATABRICKS_TOKEN
  value: DATABRICKS_TOKEN
- name: DATABRICKS_HOST
  value: DATABRICKS_HOST
